spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}

        - id: contents-service
          uri: lb://contents-service
          predicates:
            - Path=/api/v1/contents/**
          filters:
            - RewritePath=/api/v1/contents/(?<segment>.*), /api/v1/contents/${segment}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - RewritePath=/api/v1/reviews/(?<segment>.*), /api/v1/reviews/${segment}

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - RewritePath=/api/v1/reservations/(?<segment>.*), /api/v1/reservations/${segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - RewritePath=/api/v1/payments/(?<segment>.*), /api/v1/payments/${segment}

        - id: plan-service
          uri: lb://plan-service
          predicates:
            - Path=/api/v1/plans/**
          filters:
            - RewritePath=/api/v1/plans/(?<segment>.*), /api/v1/plans/${segment}

        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/boards/**
          filters:
            - RewritePath=/api/v1/boards/(?<segment>.*), /api/v1/boards/${segment}

        - id: contents-service
          uri: lb://contents-service
          predicates:
            - Path=/api/v1/contents/**
          filters:
            - RewritePath=/api/v1/contents/(?<segment>.*), /api/v1/contents/${segment}

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - RewritePath=/api/v1/coupons/(?<segment>.*), /api/v1/coupons/${segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/notifications/(?<segment>.*), /api/v1/notifications/${segment}

        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/api/v1/carts/**, Path=/api/v1/images/**
          filters:
            - RewritePath=/api/v1/carts/(?<segment>.*), /api/v1/carts/${segment}
            - RewritePath=/api/v1/images/(?<segment>.*), /api/v1/images/${segment}


jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

server:
  port: 8080