server:
  port: 38081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  #TODO: REDIS DB 분리 필요
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${TRIPLAN_EUREKA_URL}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

jwt:
  secret:
    key: ${JWT_KEY}


#kakao:
#  client_id: 8a8997adb373bd809a4e9631152c6d88
#  redirect_uri: http://localhost:8081/api/v1/users/oauth/kakao/callback