server:
  port: 38090

spring:
  application:
    name: config-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:38761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

jwt:
  secret:
    key: ${JWT_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucketName: ${AWS_BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
